import { Schema } from "effect"

export const AccountSchema = Schema.Struct({ clientId: Schema.String, walletAddress: Schema.String, availableRaw: Schema.String, lockedRaw: Schema.String, inventoryAvailableRaw: Schema.String })
export const OrderSchema = Schema.Struct({ operationId: Schema.String, clientId: Schema.String, orderType: Schema.String, quantityRaw: Schema.String, fiatCurrency: Schema.String, fiatAmountMinor: Schema.String, status: Schema.String, issuerOperationId: Schema.NullOr(Schema.String), blockchainTransactionHash: Schema.NullOr(Schema.String), lastError: Schema.NullOr(Schema.String), createdAtUnixMs: Schema.Number, updatedAtUnixMs: Schema.Number })
export const RecordItemSchema = Schema.Struct({ recordId: Schema.String, operationId: Schema.String, clientId: Schema.String, serviceType: Schema.String, orderType: Schema.String, assetSymbol: Schema.String, contractAddress: Schema.String, chainId: Schema.Number, quantityRaw: Schema.String, fiatCurrency: Schema.String, grossFiatMinor: Schema.String, feeMinor: Schema.String, status: Schema.String, sourceAccount: Schema.NullOr(Schema.String), destinationAccount: Schema.NullOr(Schema.String), blockchainTransactionHash: Schema.NullOr(Schema.String), decisionActor: Schema.String, createdAtUnixMs: Schema.Number, recordStatus: Schema.String, receivedAtUnixMs: Schema.Number, acceptedAtUnixMs: Schema.NullOr(Schema.Number), executedAtUnixMs: Schema.NullOr(Schema.Number), settledAtUnixMs: Schema.NullOr(Schema.Number), failedAtUnixMs: Schema.NullOr(Schema.Number), priceMethod: Schema.String, unitPriceMinor: Schema.NullOr(Schema.String), grossQuantityRaw: Schema.String, netQuantityRaw: Schema.String, feeQuantityRaw: Schema.String, instructionChannel: Schema.String, executionActor: Schema.String, policyVersion: Schema.String, rejectionReason: Schema.NullOr(Schema.String), retentionUntilUnixMs: Schema.Number })
export const WalletsSchema = Schema.Struct({ corporateRaw: Schema.String, hotRaw: Schema.String, coldRaw: Schema.String, evidenceBlock: Schema.NullOr(Schema.Number) })
export const ReconciliationSchema = Schema.Struct({ status: Schema.Literal("balanced", "warning", "mismatch", "unavailable"), hotRaw: Schema.NullOr(Schema.String), coldRaw: Schema.NullOr(Schema.String), corporateRaw: Schema.NullOr(Schema.String), customerAvailableRaw: Schema.NullOr(Schema.String), customerLockedRaw: Schema.NullOr(Schema.String), inventoryAvailableRaw: Schema.NullOr(Schema.String), custodyTotalRaw: Schema.NullOr(Schema.String), obligationTotalRaw: Schema.NullOr(Schema.String), differenceRaw: Schema.NullOr(Schema.String), evidenceBlock: Schema.NullOr(Schema.Number), reason: Schema.String, checkedAtUnixMs: Schema.Number, policyVersion: Schema.String })
export const TransferSchema = Schema.Struct({ operationId: Schema.String, senderClientId: Schema.String, recipientClientId: Schema.String, grossRaw: Schema.String, feeRaw: Schema.String, netRaw: Schema.String, purposeClassification: Schema.String, status: Schema.String, createdAtUnixMs: Schema.Number })
export const ExternalWithdrawalSchema = Schema.Struct({ operationId: Schema.String, clientId: Schema.String, destinationAddress: Schema.String, amountRaw: Schema.String, feeRaw: Schema.String, totalDebitRaw: Schema.String, status: Schema.String, transactionHash: Schema.NullOr(Schema.String), lastError: Schema.NullOr(Schema.String), createdAtUnixMs: Schema.Number, updatedAtUnixMs: Schema.Number })
export const FeePositionSchema = Schema.Struct({ pendingRaw: Schema.String })
export const FeeSweepSchema = Schema.Struct({ operationId: Schema.String, amountRaw: Schema.String, status: Schema.String, transactionHash: Schema.NullOr(Schema.String), lastError: Schema.NullOr(Schema.String), createdAtUnixMs: Schema.Number, updatedAtUnixMs: Schema.Number })
const ClassificationSchema = Schema.Struct({ classification: Schema.String, operationCount: Schema.Number, valueRaw: Schema.String })
const DaySchema = Schema.Struct({ dateUtc: Schema.String, assetSymbol: Schema.String, currencyArea: Schema.String, totalOperationCount: Schema.Number, totalValueRaw: Schema.String, totalValueUsdMinor: Schema.String, meansOfExchangeCount: Schema.Number, meansOfExchangeValueRaw: Schema.String, meansOfExchangeValueUsdMinor: Schema.String, meansOfExchangeValueEurMinor: Schema.String, excludedOperationCount: Schema.Number, knownOnchainOverlapCount: Schema.Number, knownOnchainOverlapValueRaw: Schema.String, classifications: Schema.Array(ClassificationSchema), methodologyVersion: Schema.String, conversionMethodology: Schema.String })
export const DailyReportSchema = Schema.Struct({ fromDateUtc: Schema.String, toDateUtc: Schema.String, days: Schema.Array(DaySchema) })
export const BootstrapSchema = Schema.Struct({ operationId: Schema.String, status: Schema.String, amountUsdMinor: Schema.String, tokenAmountRaw: Schema.String, corporateAddress: Schema.String, hotAddress: Schema.String, coldAddress: Schema.String, hotTargetRaw: Schema.String, coldTargetRaw: Schema.String, issuerTransactionHash: Schema.NullOr(Schema.String), coldTransactionHash: Schema.NullOr(Schema.String), hotTransactionHash: Schema.NullOr(Schema.String), lastError: Schema.NullOr(Schema.String), createdAtUnixMs: Schema.Number, updatedAtUnixMs: Schema.Number })
export const InventoryOperationSchema = Schema.Struct({ operationId: Schema.String, status: Schema.String, amountUsdMinor: Schema.String, tokenAmountRaw: Schema.String, hotIncrementRaw: Schema.String, coldIncrementRaw: Schema.String, hotTargetRaw: Schema.NullOr(Schema.String), coldTargetRaw: Schema.NullOr(Schema.String), issuerTransactionHash: Schema.NullOr(Schema.String), coldTransactionHash: Schema.NullOr(Schema.String), hotTransactionHash: Schema.NullOr(Schema.String), lastError: Schema.NullOr(Schema.String), createdAtUnixMs: Schema.Number, updatedAtUnixMs: Schema.Number })
export const RebalancingPlanSchema = Schema.Struct({ hotDeltaRaw: Schema.Number, coldDeltaRaw: Schema.Number, targetHotRaw: Schema.String, targetColdRaw: Schema.String, policyVersion: Schema.String })
export const RebalancingResultSchema = Schema.Struct({ direction: Schema.String, amountRaw: Schema.String, transactionHash: Schema.NullOr(Schema.String), resultingPlan: RebalancingPlanSchema })
export const TokenInformationSchema = Schema.Struct({ symbol: Schema.String, name: Schema.String, referenceCurrency: Schema.String, parityStatement: Schema.String, issuerName: Schema.String, issuerWebsite: Schema.String, issuerContactEmail: Schema.String, offerorName: Schema.String, redemptionStatement: Schema.String, redemptionFeeStatement: Schema.String, interestStatement: Schema.String, investorProtectionWarning: Schema.String, depositGuaranteeWarning: Schema.String, contractAddress: Schema.String, chainId: Schema.Number, decimals: Schema.Number, totalSupplyRaw: Schema.String, assetState: Schema.String, assetStateReason: Schema.String, reserveCoveragePercent: Schema.NullOr(Schema.Number), esgMethodologyVersion: Schema.String, esgSourceName: Schema.String, esgSourceUrl: Schema.String, esgNote: Schema.String, estimatedEnergyWh: Schema.Number, whitePaperUrl: Schema.String, issuerObservedAtUnixMs: Schema.Number, disclaimer: Schema.String })
export const ExchangeRateSchema = Schema.Struct({ usdMinorPerRusd: Schema.Number, updatedAtUnixMs: Schema.Number, methodology: Schema.String })
export const BlacklistEntrySchema = Schema.Struct({ address: Schema.String, reason: Schema.String, createdAtUnixMs: Schema.Number })
export const AccountRestrictionSchema = Schema.Struct({ clientId: Schema.String, reason: Schema.String, active: Schema.Boolean, updatedAtUnixMs: Schema.Number })
const MovementSchema = Schema.Struct({ operationId: Schema.String, occurredAtUnixMs: Schema.Number, operationType: Schema.String, status: Schema.String, availableDeltaRaw: Schema.String, lockedDeltaRaw: Schema.String, grossRaw: Schema.String, netRaw: Schema.String, feeRaw: Schema.String, counterparty: Schema.NullOr(Schema.String) })
export const ClientStatementSchema = Schema.Struct({ statementVersion: Schema.String, clientId: Schema.String, assetSymbol: Schema.String, fromDateUtc: Schema.String, toDateUtc: Schema.String, openingAvailableRaw: Schema.String, openingLockedRaw: Schema.String, closingAvailableRaw: Schema.String, closingLockedRaw: Schema.String, totalPurchasesRaw: Schema.String, totalSalesRaw: Schema.String, totalTransfersSentRaw: Schema.String, totalTransfersReceivedRaw: Schema.String, totalFeesRaw: Schema.String, totalRedemptionsRaw: Schema.String, movements: Schema.Array(MovementSchema), generatedAtUnixMs: Schema.Number, disclaimer: Schema.String })

export type Account = typeof AccountSchema.Type
export type RecordItem = typeof RecordItemSchema.Type
