import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useState } from "react"
import { AlertTriangle, Ban, Building2, CheckCircle2, Database, Server, ShieldCheck, Trash2, Users, WalletCards } from "lucide-react"
import { accountRestrictionApi, api, type RecordItem } from "./api"
import { rawToRusd } from "./amounts"
import { isFailedOperation, reconciliationDescription, reconciliationLabel, sevenDayRange } from "./features/admin/model"
import { adminQueries } from "./application/admin-queries"

const names:Record<string,string>={alice:"Alicja",bob:"Bartosz",carol:"Karolina"}

export function AdminDashboard(){
  const queryClient=useQueryClient()
  const [inventoryAmount,setInventoryAmount]=useState("1000.00")
  const [rateValue,setRateValue]=useState("1.00")
  const [blockedAddress,setBlockedAddress]=useState("")
  const [blockReason,setBlockReason]=useState("Decyzja administratora CASP")
  const [restrictedClient,setRestrictedClient]=useState("alice")
  const [restrictionReason,setRestrictionReason]=useState("Polecenie organu nadzorczego")
  const reportRange=sevenDayRange(new Date())
  const reconciliation=useQuery(adminQueries.reconciliation())
  const wallets=useQuery(adminQueries.wallets())
  const accounts=useQuery(adminQueries.accounts())
  const records=useQuery(adminQueries.records())
  const fees=useQuery(adminQueries.fees())
  const exchangeRate=useQuery({queryKey:["exchange-rate"],queryFn:api.exchangeRate})
  const blacklist=useQuery(adminQueries.blacklist())
  const accountRestrictions=useQuery(adminQueries.accountRestrictions())
  const dailyReport=useQuery(adminQueries.dailyReport(reportRange.from,reportRange.to))
  const bootstrap=useQuery(adminQueries.bootstrap())
  const replenishments=useQuery(adminQueries.replenishments())
  const plan=useQuery(adminQueries.rebalancingPlan())
  const replenish=useMutation({mutationFn:()=>api.replenish(crypto.randomUUID(),Math.round(Number(inventoryAmount)*100)),onSuccess:async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:["admin","replenishments"]}),queryClient.invalidateQueries({queryKey:["admin","wallets"]}),queryClient.invalidateQueries({queryKey:["admin","reconciliation"]}),queryClient.invalidateQueries({queryKey:["admin","accounts"]})])}})
  const sweepFees=useMutation({mutationFn:()=>api.sweepFees(crypto.randomUUID()),onSuccess:async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:["admin","fees"]}),queryClient.invalidateQueries({queryKey:["admin","wallets"]}),queryClient.invalidateQueries({queryKey:["admin","reconciliation"]})])}})
  const rebalance=useMutation({mutationFn:api.rebalance,onSuccess:async()=>{await Promise.all([queryClient.invalidateQueries({queryKey:["admin","rebalancing-plan"]}),queryClient.invalidateQueries({queryKey:["admin","wallets"]}),queryClient.invalidateQueries({queryKey:["admin","reconciliation"]})])}})
  const updateRate=useMutation({mutationFn:()=>api.setExchangeRate(Math.round(Number(rateValue)*100)),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:["exchange-rate"]})}})
  const addBlockedAddress=useMutation({mutationFn:()=>api.addToBlacklist(blockedAddress,blockReason),onSuccess:async()=>{setBlockedAddress("");await queryClient.invalidateQueries({queryKey:["admin","blacklist"]})}})
  const removeBlockedAddress=useMutation({mutationFn:(address:string)=>api.removeFromBlacklist(address),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:["admin","blacklist"]})}})
  const blockClient=useMutation({mutationFn:()=>accountRestrictionApi.block(restrictedClient,restrictionReason),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:["admin","account-restrictions"]})}})
  const unblockClient=useMutation({mutationFn:(clientId:string)=>accountRestrictionApi.unblock(clientId),onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:["admin","account-restrictions"]})}})
  const state=reconciliation.data?.status
  const error=reconciliation.error??wallets.error??accounts.error??records.error??fees.error??dailyReport.error??bootstrap.error
  const failedRecords=records.data?.filter(record=>isFailedOperation(record.status))??[]

  return <main className="casp-admin-dashboard">
    <header><div className="brand"><Building2/> CASP rUSD · panel administratora</div><a className="route-link" href="/">Widok klienta</a><span className="badge"><ShieldCheck/> demonstracja bez logowania</span></header>
    <section className="card rate-context"><div><p className="eyebrow">KURS DETALICZNY</p><h2>Parytet emitenta ≠ kurs CASP</h2><p className="hint">Emitent realizuje emisję i wykup 1:1. CASP sam ustala cenę detaliczną stosowaną przy zakupie i sprzedaży klientów.</p></div><form className="inventory-form" onSubmit={event=>{event.preventDefault();updateRate.mutate()}}><label htmlFor="exchange-rate">USD za 1 rUSD</label><input id="exchange-rate" value={rateValue} onChange={event=>setRateValue(event.target.value)} inputMode="decimal"/><button className="primary" disabled={updateRate.isPending||Number(rateValue)<=0}>{updateRate.isPending?"Zapisywanie…":"Zmień kurs"}</button><small>Aktualny kurs: {formatRate(exchangeRate.data?.usdMinorPerRusd)} USD</small></form></section>
    {error&&<section className="error-banner"><AlertTriangle/> {error.message}</section>}
    <div className="admin-workspace">
      <div className="admin-column admin-custody-column">
        <section className="admin-hero card"><div><p className="eyebrow">UZGODNIENIE SALD</p><h1>{state?reconciliationLabel(state):"Oczekiwanie na dane"}</h1><p className="hint">{state?reconciliationDescription(state):"System zbiera dane z łańcucha bloków i rejestru CASP."}</p>{state==="mismatch"&&<p className="reconciliation-difference">Wykryta różnica: <strong>{formatSigned(reconciliation.data?.differenceRaw)}</strong></p>}</div><div className={`state-orb ${state??"unavailable"}`}>{state==="balanced"?<CheckCircle2/>:<AlertTriangle/>}</div></section>
        <section className="admin-metrics">
          <AdminMetric icon={WalletCards} label="Portfel gorący" value={formatRaw(wallets.data?.hotRaw)} detail="Cel demo: 20%"/>
          <AdminMetric icon={Database} label="Portfel zimny" value={formatRaw(wallets.data?.coldRaw)} detail="Cel demo: 80%"/>
          <AdminMetric icon={Building2} label="Portfel korporacyjny" value={formatRaw(wallets.data?.corporateRaw)} detail="Środki własne CASP · poza środkami klientów"/>
        </section>
        <details className="card collapsible-card" open><summary><span><strong>Zobowiązania i zapas</strong><small>Pokrycie pozycji klientów aktywami CASP</small></span></summary><div className="collapsible-content"><div className="breakdown"><Row label="Pozycje klientów" value={formatRaw(reconciliation.data?.customerAvailableRaw)}/><Row label="Pozycje zablokowane" value={formatRaw(reconciliation.data?.customerLockedRaw)}/><Row label="Nieprzypisany zapas" value={formatRaw(reconciliation.data?.inventoryAvailableRaw)}/><Row label="Prowizje oczekujące" value={formatRaw(fees.data?.pendingRaw)}/><Row label="Łączne zobowiązanie" value={formatRaw(reconciliation.data?.obligationTotalRaw)} strong/><Row label="Portfel gorący + zimny" value={formatRaw(reconciliation.data?.custodyTotalRaw)} strong/></div><p className="policy-note">Ostatnie uzgodnienie: {reconciliation.data?new Date(reconciliation.data.checkedAtUnixMs).toLocaleString("pl-PL"):"—"}</p></div></details>
        <section className="card"><h2>Mapa klientów i przechowywanych aktywów</h2><div className="custody-graph"><div className="graph-wallet">GORĄCY + ZIMNY<strong>{formatRaw(reconciliation.data?.custodyTotalRaw)}</strong></div><div className="graph-line"/><div className="client-nodes">{accounts.data?.map(account=><div className="client-node" key={account.clientId}><Users/><span>{names[account.clientId]??account.clientId}</span><strong>{rawToRusd(account.availableRaw)} rUSD</strong><small>Zablokowane: {rawToRusd(account.lockedRaw)}</small></div>)}</div></div></section>
      </div>

      <div className="admin-column admin-inventory-column">
        <section className="card"><h2>Ręczne zwiększenie zapasu</h2><p className="hint">Zakup puli u emitenta z demonstracyjnym podziałem 20% / 80%. Automatyczne uzupełnianie jest wyłączone.</p><form className="inventory-form" onSubmit={event=>{event.preventDefault();if(Number(inventoryAmount)>0)replenish.mutate()}}><label htmlFor="inventory-amount">Kwota zakupu w USD</label><input id="inventory-amount" value={inventoryAmount} onChange={event=>setInventoryAmount(event.target.value)} inputMode="decimal"/><button className="primary" disabled={replenish.isPending||Number(inventoryAmount)<=0}>{replenish.isPending?"Realizacja…":"Kup pulę od emitenta"}</button></form>{replenish.error&&<p className="error">{replenish.error.message}</p>}<div className="breakdown"><Row label="Docelowy portfel gorący" value={formatRaw(plan.data?.targetHotRaw)}/><Row label="Docelowy portfel zimny" value={formatRaw(plan.data?.targetColdRaw)}/><Row label="Korekta gorącego" value={formatDelta(plan.data?.hotDeltaRaw)}/><Row label="Korekta zimnego" value={formatDelta(plan.data?.coldDeltaRaw)}/></div><button className="primary" disabled={rebalance.isPending||!plan.data||(plan.data.hotDeltaRaw===0&&plan.data.coldDeltaRaw===0)} onClick={()=>rebalance.mutate()}>{rebalance.isPending?"Wyrównywanie…":"Przywróć podział 20/80"}</button>{rebalance.error&&<p className="error">{rebalance.error.message}</p>}{rebalance.data&&<p className="success">Wyrównano: {formatRaw(rebalance.data.amountRaw)} · {shortHash(rebalance.data.transactionHash)}</p>}<p className="policy-note">Polityka demonstracyjna: 20% w portfelu gorącym i 80% w zimnym.</p><div className="table">{replenishments.data?.slice(0,5).map(operation=><article key={operation.operationId}><div><strong>{formatMinor(operation.amountUsdMinor)} USD</strong><small>{operation.operationId}</small></div><span className={`status ${operation.status==="completed"?"completed":""}`}>{operationStatusLabel(operation.status)}</span></article>)}</div></section>
        <section className="card fee-sweep"><div><p className="eyebrow">PROWIZJE CASP</p><h2>{formatRaw(fees.data?.pendingRaw)} do przeniesienia</h2><p className="hint">Transfer z portfela gorącego do korporacyjnego.</p></div><button className="primary" disabled={sweepFees.isPending||!fees.data||Number(fees.data.pendingRaw)===0} onClick={()=>sweepFees.mutate()}>{sweepFees.isPending?"Przenoszenie…":"Przenieś prowizje"}</button>{sweepFees.error&&<p className="error">{sweepFees.error.message}</p>}{sweepFees.data&&<p className="success">Przeniesiono {formatRaw(sweepFees.data.amountRaw)} · {shortHash(sweepFees.data.transactionHash)}</p>}</section>
        <details className="card collapsible-card" open><summary><span className="section-heading"><Ban/><span><strong>Czarna lista adresów</strong><small>Blokowanie adresów zewnętrznych</small></span></span></summary><div className="collapsible-content"><p className="hint">Blokuje operacje obsługiwane przez CASP z danego adresu i na ten adres.</p><form className="blacklist-form" onSubmit={event=>{event.preventDefault();addBlockedAddress.mutate()}}><label>Adres portfela<input value={blockedAddress} onChange={event=>setBlockedAddress(event.target.value)} placeholder="0x…" spellCheck={false}/></label><label>Uzasadnienie<input value={blockReason} onChange={event=>setBlockReason(event.target.value)}/></label><button className="primary" disabled={addBlockedAddress.isPending||!blockedAddress.trim()||!blockReason.trim()}>Dodaj do czarnej listy</button></form>{addBlockedAddress.error&&<p className="error">{addBlockedAddress.error.message}</p>}<div className="blacklist-items">{blacklist.data?.map(entry=><article key={entry.address}><div><strong>{entry.address}</strong><small>{entry.reason}</small></div><button title="Usuń blokadę" onClick={()=>removeBlockedAddress.mutate(entry.address)}><Trash2/></button></article>)}{blacklist.data?.length===0&&<p className="empty-state">Czarna lista jest pusta.</p>}</div></div></details>
        <details className="card collapsible-card" open><summary><span className="section-heading"><Users/><span><strong>Blokady kont klientów</strong><small>Wstrzymanie operacji wybranego klienta</small></span></span></summary><div className="collapsible-content"><p className="hint">Wstrzymuje wszystkie operacje klienta oraz księgowanie przelewów na jego konto.</p><form className="blacklist-form" onSubmit={event=>{event.preventDefault();blockClient.mutate()}}><label>Klient<select value={restrictedClient} onChange={event=>setRestrictedClient(event.target.value)}>{Object.entries(names).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Uzasadnienie<input value={restrictionReason} onChange={event=>setRestrictionReason(event.target.value)}/></label><button className="primary" disabled={blockClient.isPending||!restrictionReason.trim()}>Zablokuj konto klienta</button></form>{blockClient.error&&<p className="error">{blockClient.error.message}</p>}<div className="blacklist-items">{accountRestrictions.data?.map(entry=><article key={entry.clientId}><div><strong>{names[entry.clientId]??entry.clientId}</strong><small>{entry.reason}</small></div><button title="Odblokuj konto" onClick={()=>unblockClient.mutate(entry.clientId)}><Trash2/></button></article>)}{accountRestrictions.data?.length===0&&<p className="empty-state">Żadne konto klienta nie jest zablokowane.</p>}</div></div></details>
        <details className="card collapsible-card" open><summary><span className="section-heading"><Server/><span><strong>Zakup zapasu u emitenta</strong><small>Stan zlecenia emisji i przekazania tokenów</small></span></span></summary><div className="collapsible-content"><p className="hint">Sekcja przedstawia proces zwiększania zapasu CASP: utworzenie zlecenia u emitenta, symulowaną wpłatę USD, emisję rUSD na portfel gorący oraz późniejsze rozdzielenie tokenów między portfele gorący i zimny.</p><div className="integration-status"><Server/><div><strong>{operationStatusLabel(bootstrap.data?.status??"brak danych")}</strong><p className="hint">Identyfikator zakupu początkowego: {bootstrap.data?.operationId??"—"}</p></div></div>{bootstrap.data?.lastError?<p className="error">Operacja wymaga sprawdzenia w dziennikach technicznych.</p>:failedRecords.length?<p className="error">Nieudane operacje: {failedRecords.length}</p>:<p className="success">Proces zakupu zapasu nie zgłasza błędów.</p>}<p className="hint">Identyfikator transakcji emisji: {shortHash(bootstrap.data?.issuerTransactionHash)}</p></div></details>
      </div>

      <div className="admin-column admin-audit-column">
        <section className="card"><h2>Ostatnie operacje</h2><p className="hint">Rejestr audytowy usług CASP — nie jest źródłem sald.</p><div className="operation-flow">{records.data?.slice(0,6).map(record=><Operation key={record.recordId} record={record}/>)}</div>{records.data?.length===0&&<p className="empty-state">Brak zarejestrowanych operacji klientów.</p>}</section>
        <details className="card collapsible-card" open><summary><span><strong>Raportowanie dzienne</strong><small>Agregaty przekazywane emitentowi</small></span></summary><div className="collapsible-content"><p className="hint">Agregat udostępniany emitentowi; operacje wymiany waluty fiducjarnej są wykluczone z estymaty środka wymiany.</p><div className="daily-report">{dailyReport.data?.days.map(day=><article key={day.dateUtc}><strong>{day.dateUtc}</strong><span>Wszystkie operacje: {day.totalOperationCount}</span><span>Środek wymiany: {day.meansOfExchangeCount}</span><span>Wartość: {formatMinor(day.meansOfExchangeValueUsdMinor)} USD</span><small>Metoda demonstracyjna · przelicznik USD/EUR 1:1</small></article>)}</div>{dailyReport.data?.days.length===0&&<p className="empty-state">Brak aktywności w ostatnich siedmiu dniach.</p>}</div></details>
      </div>
    </div>
  </main>
}

function AdminMetric({icon:Icon,label,value,detail}:{icon:typeof ShieldCheck;label:string;value:string;detail:string}){return <article className="card admin-metric"><Icon/><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={strong?"summary-row strong":"summary-row"}><span>{label}</span><b>{value}</b></div>}
function Operation({record}:{record:RecordItem}){return <article className={`operation ${isFailedOperation(record.status)?"failed":""}`}><div className="operation-route"><span>{names[record.sourceAccount??""]??record.sourceAccount??"CASP"}</span><i>→</i><span>{names[record.destinationAccount??""]??record.destinationAccount??"CASP"}</span></div><strong>{rawToRusd(record.netQuantityRaw)} rUSD</strong><small>{operationLabel(record.orderType)} · {new Date(record.receivedAtUnixMs).toLocaleString("pl-PL")}</small><small>{priceMethodLabel(record.priceMethod)} · kanał: panel demonstracyjny</small><span className="operation-status">{operationStatusLabel(record.status)}</span></article>}
function formatRaw(value:string|undefined|null){return value===undefined||value===null?"—":`${rawToRusd(value)} rUSD`}
function formatSigned(value:string|undefined|null){if(value===undefined||value===null)return "—";const number=Number(value)/1_000_000;return `${number>0?"+":""}${number.toLocaleString("pl-PL",{maximumFractionDigits:6})} rUSD`}
function shortHash(value:string|undefined|null){return value?`${value.slice(0,10)}…${value.slice(-6)}`:"—"}
function priceMethodLabel(value:string){return value==="not_applicable"?"kurs nie dotyczy":value==="casp_admin_configured_rate"?"kurs ustalony przez CASP":"metoda historyczna"}
function formatRate(value:number|undefined){return ((value??100)/100).toLocaleString("pl-PL",{minimumFractionDigits:2,maximumFractionDigits:2})}
function operationLabel(value:string){return {purchase:"zakup",sale:"sprzedaż",internal_transfer:"przelew wewnętrzny",external_deposit:"wpłata zewnętrzna",external_withdrawal:"wypłata na portfel",redemption:"wykup u emitenta"}[value]??value}
function operationStatusLabel(value:string){return {created:"utworzona",issuer_order_created:"zlecenie utworzone u emitenta",fiat_sent:"wpłata USD przekazana",tokens_issued:"tokeny wyemitowane",targets_recorded:"zapisano docelowy podział",cold_distributed:"przeniesiono część do portfela zimnego",distributed:"tokeny rozdzielone",completed:"zakończona",pending:"oczekująca",processing:"przetwarzana",failed:"nieudana",rejected:"odrzucona",cancelled:"anulowana"}[value.toLowerCase()]??value}
function formatMinor(value:string){return (Number(value)/100).toLocaleString("pl-PL",{minimumFractionDigits:2,maximumFractionDigits:2})}
function formatDelta(value:number|undefined){if(value===undefined)return "—";return `${value>0?"+":""}${rawToRusd(String(value))} rUSD`}
