import { Effect, Schema } from "effect"

const Account=Schema.Struct({clientId:Schema.String,availableRaw:Schema.String,lockedRaw:Schema.String,inventoryAvailableRaw:Schema.String})
const Order=Schema.Struct({operationId:Schema.String,clientId:Schema.String,orderType:Schema.String,quantityRaw:Schema.String,fiatCurrency:Schema.String,fiatAmountMinor:Schema.String,status:Schema.String,issuerOperationId:Schema.NullOr(Schema.String),blockchainTransactionHash:Schema.NullOr(Schema.String),lastError:Schema.NullOr(Schema.String),createdAtUnixMs:Schema.Number,updatedAtUnixMs:Schema.Number})
const RecordItem=Schema.Struct({recordId:Schema.String,operationId:Schema.String,clientId:Schema.String,serviceType:Schema.String,orderType:Schema.String,assetSymbol:Schema.String,contractAddress:Schema.String,chainId:Schema.Number,quantityRaw:Schema.String,fiatCurrency:Schema.String,grossFiatMinor:Schema.String,feeMinor:Schema.String,status:Schema.String,sourceAccount:Schema.NullOr(Schema.String),destinationAccount:Schema.NullOr(Schema.String),blockchainTransactionHash:Schema.NullOr(Schema.String),decisionActor:Schema.String,createdAtUnixMs:Schema.Number})
const Wallets=Schema.Struct({corporateRaw:Schema.String,hotRaw:Schema.String,coldRaw:Schema.String,evidenceBlock:Schema.NullOr(Schema.Number)})
const Reconciliation=Schema.Struct({status:Schema.Literal("balanced","warning","blocked","unavailable"),hotRaw:Schema.NullOr(Schema.String),coldRaw:Schema.NullOr(Schema.String),corporateRaw:Schema.NullOr(Schema.String),customerAvailableRaw:Schema.NullOr(Schema.String),customerLockedRaw:Schema.NullOr(Schema.String),inventoryAvailableRaw:Schema.NullOr(Schema.String),custodyTotalRaw:Schema.NullOr(Schema.String),obligationTotalRaw:Schema.NullOr(Schema.String),differenceRaw:Schema.NullOr(Schema.String),evidenceBlock:Schema.NullOr(Schema.Number),reason:Schema.String,checkedAtUnixMs:Schema.Number,policyVersion:Schema.String})
const Transfer=Schema.Struct({operationId:Schema.String,senderClientId:Schema.String,recipientClientId:Schema.String,grossRaw:Schema.String,feeRaw:Schema.String,netRaw:Schema.String,purposeClassification:Schema.String,status:Schema.String,createdAtUnixMs:Schema.Number})
const FeePosition=Schema.Struct({pendingRaw:Schema.String})
const Bootstrap=Schema.Struct({operationId:Schema.String,status:Schema.String,amountUsdMinor:Schema.String,tokenAmountRaw:Schema.String,corporateAddress:Schema.String,hotAddress:Schema.String,coldAddress:Schema.String,hotTargetRaw:Schema.String,coldTargetRaw:Schema.String,issuerTransactionHash:Schema.NullOr(Schema.String),coldTransactionHash:Schema.NullOr(Schema.String),hotTransactionHash:Schema.NullOr(Schema.String),lastError:Schema.NullOr(Schema.String),createdAtUnixMs:Schema.Number,updatedAtUnixMs:Schema.Number})
export type Account=typeof Account.Type
export type RecordItem=typeof RecordItem.Type

const request=<A>(path:string,init:RequestInit|undefined,schema:Schema.Schema<A>)=>Effect.runPromise(Effect.gen(function*(){const response=yield* Effect.tryPromise({try:()=>fetch(path,init),catch:()=>new Error("Backend CASP jest niedostępny")});if(!response.ok){const text=yield* Effect.tryPromise({try:()=>response.text(),catch:()=>new Error(`Błąd HTTP ${response.status}`)});let message=`Błąd HTTP ${response.status}`;try{const body=JSON.parse(text) as {error?:unknown};if(typeof body.error==="string")message=body.error}catch{/* The proxy or server may return a non-JSON error page. */}return yield* Effect.fail(new Error(message))}const json=yield* Effect.tryPromise({try:()=>response.json(),catch:()=>new Error("Backend CASP zwrócił niepoprawną odpowiedź JSON")});return yield* Schema.decodeUnknown(schema)(json)}))
const json=(value:unknown):RequestInit=>({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(value)})
const clientPath=(clientId:string)=>`/api/v1/clients/${encodeURIComponent(clientId)}`
export const api={accounts:()=>request("/api/v1/clients",undefined,Schema.Array(Account)),account:(clientId:string)=>request(`${clientPath(clientId)}/account`,undefined,Account),records:(clientId:string)=>request(`${clientPath(clientId)}/records`,undefined,Schema.Array(RecordItem)),purchase:(clientId:string,operationId:string,amountUsdMinor:number)=>request(`${clientPath(clientId)}/purchases`,json({operationId,amountUsdMinor}),Order),sale:(clientId:string,operationId:string,tokenAmountRaw:number)=>request(`${clientPath(clientId)}/sales`,json({operationId,tokenAmountRaw}),Order),transfer:(clientId:string,operationId:string,recipientClientId:string,tokenAmountRaw:number,purposeClassification:string)=>request(`${clientPath(clientId)}/transfers`,json({operationId,recipientClientId,tokenAmountRaw,purposeClassification}),Transfer),bootstrap:()=>request("/api/v1/admin/bootstrap-inventory",{method:"POST"},Schema.Unknown),bootstrapStatus:()=>request("/api/v1/admin/bootstrap-inventory",undefined,Bootstrap),wallets:()=>request("/api/v1/admin/wallets",undefined,Wallets),reconciliation:()=>request("/api/v1/admin/reconciliation",undefined,Reconciliation),fees:()=>request("/api/v1/admin/fees",undefined,FeePosition)}
