import { Effect, Schema } from "effect"

const Account=Schema.Struct({clientId:Schema.String,availableRaw:Schema.String,lockedRaw:Schema.String,inventoryAvailableRaw:Schema.String})
const Order=Schema.Struct({operationId:Schema.String,clientId:Schema.String,orderType:Schema.String,quantityRaw:Schema.String,fiatCurrency:Schema.String,fiatAmountMinor:Schema.String,status:Schema.String,issuerOperationId:Schema.NullOr(Schema.String),blockchainTransactionHash:Schema.NullOr(Schema.String),lastError:Schema.NullOr(Schema.String),createdAtUnixMs:Schema.Number,updatedAtUnixMs:Schema.Number})
const RecordItem=Schema.Struct({recordId:Schema.String,operationId:Schema.String,clientId:Schema.String,serviceType:Schema.String,orderType:Schema.String,assetSymbol:Schema.String,contractAddress:Schema.String,chainId:Schema.Number,quantityRaw:Schema.String,fiatCurrency:Schema.String,grossFiatMinor:Schema.String,feeMinor:Schema.String,status:Schema.String,sourceAccount:Schema.NullOr(Schema.String),destinationAccount:Schema.NullOr(Schema.String),blockchainTransactionHash:Schema.NullOr(Schema.String),decisionActor:Schema.String,createdAtUnixMs:Schema.Number})
export type Account=typeof Account.Type
export type RecordItem=typeof RecordItem.Type

const request=<A>(path:string,init:RequestInit|undefined,schema:Schema.Schema<A>)=>Effect.runPromise(Effect.gen(function*(){const response=yield* Effect.tryPromise({try:()=>fetch(path,init),catch:()=>new Error("Backend CASP jest niedostępny")});if(!response.ok){const body=yield* Effect.tryPromise(()=>response.json() as Promise<{error?:string}>);return yield* Effect.fail(new Error(body.error??`Błąd HTTP ${response.status}`))}const json=yield* Effect.tryPromise(()=>response.json());return yield* Schema.decodeUnknown(schema)(json)}))
const json=(value:unknown):RequestInit=>({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(value)})
const clientPath=(clientId:string)=>`/api/v1/clients/${encodeURIComponent(clientId)}`
export const api={accounts:()=>request("/api/v1/clients",undefined,Schema.Array(Account)),account:(clientId:string)=>request(`${clientPath(clientId)}/account`,undefined,Account),records:(clientId:string)=>request(`${clientPath(clientId)}/records`,undefined,Schema.Array(RecordItem)),purchase:(clientId:string,operationId:string,amountUsdMinor:number)=>request(`${clientPath(clientId)}/purchases`,json({operationId,amountUsdMinor}),Order),sale:(clientId:string,operationId:string,tokenAmountRaw:number)=>request(`${clientPath(clientId)}/sales`,json({operationId,tokenAmountRaw}),Order),bootstrap:()=>request("/api/v1/admin/bootstrap-inventory",{method:"POST"},Schema.Unknown)}
