import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { ArrowDownToLine, ArrowUpFromLine, Building2, RefreshCw, Send, ShieldCheck, UserRound, WalletCards } from "lucide-react"
import { FormEvent, useEffect, useState } from "react"
import { api } from "./api"
import { rawToRusd, usdToMinor, usdToRaw } from "./amounts"
import { AdminDashboard } from "./admin-dashboard"
import { StatementPage } from "./statement"
import "./token-info.css"

const clients: Record<string,string>={alice:"Alicja Kowalska",bob:"Bartosz Nowak",carol:"Karolina Wiśniewska"}

export function App(){
  return window.location.pathname.startsWith("/admin")?<AdminDashboard/>:window.location.pathname.startsWith("/statement")?<StatementPage/>:<CustomerApp/>
}

function CustomerApp(){
  const queryClient=useQueryClient()
  const [clientId,setClientId]=useState("alice")
  const [mode,setMode]=useState<"purchase"|"sale"|"transfer"|"withdrawal">("purchase")
  const [amount,setAmount]=useState("100.00")
  const [recipientId,setRecipientId]=useState("bob")
  const [purpose,setPurpose]=useState("private_transfer")
  const [destinationAddress,setDestinationAddress]=useState("0x90F79bf6EB2c4f870365E785982E1f101E93b906")
  const account=useQuery({queryKey:["account",clientId],queryFn:()=>api.account(clientId),refetchInterval:3000})
  const accounts=useQuery({queryKey:["accounts"],queryFn:api.accounts,refetchInterval:3000})
  const records=useQuery({queryKey:["records",clientId],queryFn:()=>api.records(clientId),refetchInterval:3000})
  const tokenInfo=useQuery({queryKey:["token-information"],queryFn:api.tokenInformation,refetchInterval:10_000})
  const exchangeRate=useQuery({queryKey:["exchange-rate"],queryFn:api.exchangeRate,refetchInterval:10_000})
  const recipientWallet=accounts.data?.find(item=>item.clientId===recipientId)?.walletAddress??recipientId
  const purchaseBlocked=mode==="purchase"&&tokenInfo.data?.assetState==="wind_down"
  useEffect(()=>{if(purchaseBlocked)setMode("sale")},[purchaseBlocked])
  const mutation=useMutation<unknown,Error>({mutationFn:()=>mode==="purchase"?api.purchase(clientId,crypto.randomUUID(),usdToMinor(amount)):mode==="sale"?api.sale(clientId,crypto.randomUUID(),usdToRaw(amount)):mode==="transfer"?api.transfer(clientId,crypto.randomUUID(),recipientWallet,usdToRaw(amount),purpose):api.externalWithdrawal(clientId,crypto.randomUUID(),destinationAddress,usdToRaw(amount)),onSuccess:()=>queryClient.invalidateQueries()})
  const submit=(event:FormEvent)=>{event.preventDefault();if(!purchaseBlocked)mutation.mutate()}
  const changeClient=(value:string)=>{setClientId(value);if(recipientId===value)setRecipientId(Object.keys(clients).find(id=>id!==value)??"alice");mutation.reset()}
  return <main className="customer-dashboard">
    <header><div className="brand"><Building2/> rUSD CASP</div><div className="account-switcher"><UserRound/><label htmlFor="client">Testuj jako</label><select id="client" value={clientId} onChange={event=>changeClient(event.target.value)}>{Object.entries(clients).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></div><a className="route-link" href={`/statement?client=${clientId}`}>Wyciąg klienta</a><a className="route-link" href="/admin">Panel administratora</a><span className="badge"><ShieldCheck/> środowisko demonstracyjne</span></header>
    <div className="customer-workspace">
      <section className="customer-account-column">
        <section className="hero"><div><p className="eyebrow">KONTO: {clients[clientId].toUpperCase()}</p><h1>{account.data?rawToRusd(account.data.availableRaw):"—"} rUSD</h1><p>Prawo klienta do części tokenów przechowywanych przez CASP</p><p className="wallet-address">Logiczny adres odbiorczy: <strong>{account.data?.walletAddress??"—"}</strong></p></div><div className="locked">Zablokowane<strong>{account.data?rawToRusd(account.data.lockedRaw):"—"} rUSD</strong></div></section>
        <section className="card token-info"><h2>Najważniejsze informacje o rUSD</h2>{tokenInfo.data?<><div className={`token-public-state ${tokenInfo.data.assetState}`}><span>Status tokenu</span><strong>{assetStateLabel(tokenInfo.data.assetState)}</strong><small>{assetStateDescription(tokenInfo.data.assetState)}</small></div><dl className="token-facts"><div><dt>Emitent</dt><dd>{tokenInfo.data.issuerName}</dd></div><div><dt>Waluta odniesienia</dt><dd>{tokenInfo.data.referenceCurrency}</dd></div><div><dt>Emisja i wykup</dt><dd>1 rUSD = 1 USD</dd></div><div><dt>Oferujący</dt><dd>{tokenInfo.data.offerorName}</dd></div></dl><div className="holder-rights"><strong>Prawa posiadacza</strong><p>{tokenInfo.data.redemptionStatement}</p><p>{tokenInfo.data.redemptionFeeStatement}</p><p>{tokenInfo.data.interestStatement}</p></div><div className="token-warnings"><p>{tokenInfo.data.investorProtectionWarning}</p><p>{tokenInfo.data.depositGuaranteeWarning}</p></div><div className="esg-customer-summary"><div><span>Estymowane dzienne zużycie energii</span><strong>{formatEnergy(tokenInfo.data.estimatedEnergyWh)}</strong></div><small>Estymata przypisana aktywności tokenu, nie bezpośredni pomiar.</small></div><div className="token-info-links"><a className="route-link" href={tokenInfo.data.whitePaperUrl} target="_blank" rel="noreferrer">Dokument informacyjny</a><a href={`mailto:${tokenInfo.data.issuerContactEmail}`}>Kontakt z emitentem</a></div></>:<p className="hint">{tokenInfo.error?"Nie udało się pobrać informacji o tokenie.":"Pobieranie informacji od emitenta…"}</p>}</section>
      </section>
        <section className="card customer-operation-column"><nav><button className={mode==="purchase"?"active":""} onClick={()=>setMode("purchase")}><ArrowDownToLine/> Kup</button><button className={mode==="sale"?"active":""} onClick={()=>setMode("sale")}><ArrowUpFromLine/> Sprzedaj</button><button className={mode==="transfer"?"active":""} onClick={()=>setMode("transfer")}><Send/> W CASP</button><button className={mode==="withdrawal"?"active":""} onClick={()=>setMode("withdrawal")}><WalletCards/> Do portfela</button></nav><form onSubmit={submit}><label>{mode==="transfer"?"Kwota brutto w rUSD":mode==="withdrawal"?"Kwota wysyłana na portfel":mode==="purchase"?"Kwota płatności w USD":"Liczba sprzedawanych rUSD"}</label><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/>{mode==="transfer"&&<div className="transfer-fields"><label>Odbiorca<select value={recipientId} onChange={event=>setRecipientId(event.target.value)}>{Object.entries(clients).filter(([id])=>id!==clientId).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Cel przelewu<select value={purpose} onChange={event=>setPurpose(event.target.value)}><option value="private_transfer">Przelew prywatny</option><option value="goods_or_services">Towary lub usługi</option></select></label></div>}{mode==="withdrawal"&&<label>Adres portfela Ethereum<input value={destinationAddress} onChange={event=>setDestinationAddress(event.target.value)} spellCheck={false}/></label>}{(mode==="purchase"||mode==="sale")&&<div className="exchange-rate"><span>Kurs transakcyjny CASP · demonstracja</span><strong>1 rUSD = {formatRate(exchangeRate.data?.usdMinorPerRusd)} USD</strong><small>CASP ustala cenę kupna i sprzedaży dla klienta. Może ona różnić się od parytetu wykupu u emitenta.</small></div>}<p className="hint">{mode==="transfer"?"Przelew jest operacją w wewnętrznym rejestrze CASP i nie wymaga opłaty sieciowej. Z kwoty brutto pobierana jest demonstracyjna opłata transakcyjna 0,1%; odbiorca otrzymuje kwotę netto.":mode==="withdrawal"?"CASP wyśle wskazaną kwotę rUSD z gorącego portfela. Z salda klienta zostanie dodatkowo pobrana demonstracyjna prowizja 1%; koszt sieciowy pokrywa CASP.":"Zakup i sprzedaż aktualizują wyłącznie wewnętrzny rejestr CASP — bez transakcji w łańcuchu bloków. Wyświetlany kurs jest ofertą CASP, a nie gwarancją emitenta."}</p><button className="primary" disabled={mutation.isPending}>{mutation.isPending?<><RefreshCw className="spin"/> Przetwarzanie…</>:mode==="purchase"?"Kup rUSD":mode==="sale"?"Sprzedaj rUSD":mode==="withdrawal"?"Wyślij na portfel":"Przelej rUSD"}</button>{mutation.error&&<p className="error">{mutation.error.message}</p>}{mutation.isSuccess&&<p className="success">Operacja zakończona i zapisana w rejestrze.</p>}</form></section>
      <section className="card history customer-history-column"><h2>Rejestr operacji</h2><p className="hint">Historia konta {clients[clientId]}. Kwota otrzymanego przelewu uwzględnia potrąconą prowizję.</p><div className="table">{records.data?.map(record=><CustomerRecord key={record.recordId} record={record} clientId={clientId}/>)}{records.data?.length===0&&<p>Brak operacji.</p>}</div></section>
    </div>
  </main>
}
function formatRate(value:number|undefined){return ((value??100)/100).toLocaleString("pl-PL",{minimumFractionDigits:2,maximumFractionDigits:2})}
function formatEnergy(value:number){return `${value.toLocaleString("pl-PL",{maximumFractionDigits:2})} Wh`}
function assetStateLabel(value:string){return {active:"Aktywny",warning:"Ostrzeżenie",mint_blocked:"Emisja zablokowana",data_unavailable:"Brak danych",wind_down:"Wygaszanie"}[value]??value}
function assetStateDescription(value:string){return value==="wind_down"?"Nie można kupować nowych rUSD. Sprzedaż i wyjście klienta pozostają dostępne.":value==="mint_blocked"?"Emitent nie może tworzyć nowych tokenów; obrót istniejącą pulą CASP pozostaje dostępny.":value==="warning"?"Token działa, ale emitent wskazuje podwyższone ryzyko.":value==="active"?"Token działa bez aktywnej blokady cyklu życia.":"Nie udało się potwierdzić bieżącego stanu tokenu."}
function CustomerRecord({record,clientId}:{record:import("./api").RecordItem;clientId:string}){const transfer=record.orderType==="internal_transfer";const sent=transfer&&record.sourceAccount===clientId;const received=transfer&&record.destinationAccount===clientId;const deposit=record.orderType==="external_deposit";const withdrawal=record.orderType==="external_withdrawal";const amount=(received||withdrawal)?record.netQuantityRaw:record.grossQuantityRaw;const title=sent?"Wysłano przelew":received?"Otrzymano przelew":deposit?"Wpłata zewnętrzna":withdrawal?"Wypłata na portfel":record.orderType==="purchase"?"Zakup":record.orderType==="sale"?"Sprzedaż":"Wykup";return <article><div><strong>{title} · {rawToRusd(amount)} rUSD</strong>{(sent||withdrawal)&&Number(record.feeQuantityRaw)>0&&<small>Prowizja CASP: {rawToRusd(record.feeQuantityRaw)} rUSD{sent&&` · odbiorca otrzymał ${rawToRusd(record.netQuantityRaw)} rUSD`}</small>}{deposit&&<small>Nadawca w łańcuchu bloków: {record.sourceAccount??"—"}</small>}{withdrawal&&<small>Adres docelowy: {record.destinationAccount} · {record.blockchainTransactionHash}</small>}<small>{new Date(record.createdAtUnixMs).toLocaleString("pl-PL")} · {record.operationId}</small></div><span className={`status ${record.status}`}>{record.status==="completed"?"zakończona":record.status}</span></article>}
